### ISSUE TITLE
Boopickle modifies original ByteOrder 

### ISSUE THREAD

**Issue by slandelle** [ochrons/boopickle#15]
Hi,

It's probably quite common to have to mix pickling with writing raw bytes/ints. A typical example is prepending a frame length length.

Being the default on the JVM, and for compatibility with other libraries (Netty in my case), I would like to be able to use BigEndian.

But then, I ran into some issue because Boopickle changes the byte order of the ByteBuffer it's being feed. I believe it happens [here](https://github.com/ochrons/boopickle/blob/bf1c36c4cabac432a9fd719cc112215f0bf71c10/boopickle/shared/src/main/scala/boopickle/Codecs.scala#L203).

I was able to work around this by restoring the original byte order before reading raw data, but this sure is tricky. If possible, it would be more convenient if Boopickle could honor the original byte order.

Regards.

**Comment by ochrons** [comment]
Yeah, this is a known issue. Problem is that BooPickle cannot `duplicate()` the ByteBuffer, because then the original one is not "moving ahead" when data is read. I suppose it could store original byte order and restore it after unpickling.

The problem is actually [here](https://github.com/ochrons/boopickle/blob/bf1c36c4cabac432a9fd719cc112215f0bf71c10/boopickle/shared/src/main/scala/boopickle/Unpickler.scala#L20)

Little-endian order is used by BooPickle because it has better performance on today's Intel and ARM architectures. The JVM default dates back to Sun and its SPARC processors :)

**Comment by slandelle** [comment]
Thanks Otto.

I will try to find a way to enforce Little-Endian on the other libraries that work around BooPickle on my side.

But IMHO, it's perfectly fine that BooPickle uses Little-Endian internally, but it would be better if it could be more hygienic.
Maybe having the main entry points (`Pickle.fromBytes` and `Unpickle.fromBytes`) first force Little-endian, do the job, then restore the original byte order would suffice?

**Comment by ochrons** [comment]
I'll make those modifications in the next release. BooPickle also needs to store byte-order information about a `ByteBuffer` that is pickled (in encoder/decoder) which is a related problem.

**Comment by slandelle** [comment]
Great, thanks! Please let me know if I can help/test.
