### ISSUE TITLE
Use a recyclable ByteBuffer for encoding Strings

### ISSUE THREAD

**Issue by slandelle** [ochrons/boopickle#5]
On my (private, sorry, will try to extract) benchmark, BooPickle is about 10% slower than MessagePack.

I suspect this comes from the way BooPickle packs Strings: standard `String#getBytes(Charset)`.

MessagePack uses a dedicated recycled `ByteBuffer` and also keep a reference to the `CharsetEncoder`.
Those could probably be stored in the state, right?

**Comment by ochrons** [comment]
The charset is already a static reference defined in `StandardCharsets` as

```public static final Charset UTF_8 = Charset.forName("UTF-8");```

I doubt there is any need to recycle a ByteBuffer for strings, since it's just wrapping the produced byte array into a ByteBuffer (no copying here) and then that is copied into the Encoder's ByteBuffer.

You can test this by using very long strings, to see if there is any big difference.

The string coding is slow mainly because encoder has special codings for numerical and UUID strings, which are checked for every string encoded. The checks tend to be very fast, but for small strings it will still take some time.

Anyway, BooPickle prefers low byte count at the expense of encoding time because it's intended for client-server communication where the server is powerful, but network and client are limited.

Use of Direct ByteBuffers allows for better performance when that buffer is sent to I/O at some point (and are required on Scala.js to get access to Typed Arrays). On the other hand, allocation of DBBs is much slower than heap buffers. So if you encode a lot of small things one by one, it's probably a bit slower.

**Comment by slandelle** [comment]
> The charset is already a static reference

I'm talking about the underlying CharsetEncoder.

> I doubt there is any need to recycle a ByteBuffer for strings, since it's just wrapping the produced byte array into a ByteBuffer (no copying here) and then that is copied into the Encoder's ByteBuffer.

Have a look at how String.getBytes is implemented: it creates a new CharsetEncoder, allocates some bytes, encodes into it, and then reallocate a new one with the exact size to trim it down. So yes, it involves a copy that you would save if you were directly using a CharsetEncoder and using it to decode into a ByteBuffer. And this same ByteBuffer could be recycled. That's what MessagePack does.

> Use of Direct ByteBuffers allows for better performance when that buffer is sent to I/O at some point (and are required on Scala.js to get access to Typed Arrays). On the other hand, allocation of DBBs is much slower than heap buffers.

In my use case, as I pack and then compress (which you also do in your benchmark), using direct buffers is slower as it forces to copy the bytes out of the direct ByteBuffer because Deflater takes a byte array. 

Different use cases, different needs. It looks to me it could be easily made configurable, see #4 

> So if you encode a lot of small things one by one, it's probably a bit slower.

Absolutely. I have payloads that mix Strings and numbers, things like Map[String, Int].

**Comment by ochrons** [comment]
Ok, I see what you mean. Yeah, that could indeed improve the performance. Of course special care has to be taken to ensure thread-safe operation when using recycled buffers (thread local storage, for example).

**Comment by slandelle** [comment]
Before going with a global caching (threadLocal), maybe caching it in the `PickleState` would be a first step.

There's another possibility: write the String length header unpacked. This way, we could:
* save the current position
* move the position 4 bytes forward
* directly encode the String into the main ByteBuffer
* put the encoded String length at the saved position

This way, we would save the the intermediate buffer and the intermediate copy. But we would lose some space on short Strings where length would fit in less than 4 bytes.

**Comment by ochrons** [comment]
That would be quite speedy indeed, but would waste space (which is 1st priority in BooPickle). Also copying strings that have just been encoded is fast anyway since they are in the cache.

**Comment by slandelle** [comment]
I was expecting this answer. ;-)

So what about caching in the PickleState?

**Comment by ochrons** [comment]
It should be cached in the `Encoder`. But this would mean changing the platform specific `StringCodec` as well, which is currently stateless. On the JS side none of this really matters as it is using `TextEncoder` whenever possible (and encoding performance is not that important there), so this would be a JVM-only optimization.

**Comment by slandelle** [comment]
> But this would mean changing the platform specific StringCodec as well, which is currently stateless.

It can still be stateless if methods are changed from `encode/decode` to `encodeInto/decodeInto` and be passed the (initial, as the codec might have to expand it) target ByteBuffer.

**Comment by ochrons** [comment]
I tested using `CharsetEncoder` directly but it provided no measurable benefit. Using heap bytebuffers (see resolved #4) gives a nice 10-20% boost to encoding small data.
