### ISSUE TITLE
Claim you're the fastest ever? Weaken your claims or prove it.

### ISSUE THREAD

**Issue by heathermiller** [ochrons/boopickle#55]
I find the READE me rather arrogant.

> BooPickle is the fastest and most size efficient serialization (aka pickling) library for Scala and Scala.js.

Doubt that it's the fastest library for Scala. There are significantly more serialization libraries than you're benchmarking against. While my experience is limited to Scala Pickling, I can attest that Scala Pickling was benchmarked to be up to 6x faster than Kryo, so it was faster than mainstream Java serialization frameworks as well. We've not done any performance regression testing and have done a lot of refactoring in the past year or so, so it could be that something we did in the past year or so might've killed that lead that we had. But I still seriously doubt your 5/1000/10000 element microbenchmarks and your over the top claims that boopickle is the fastest serialization library in the world. As far as benchmarking serialization goes, these nanobenchmarks will tell you little.

But don't go claiming you're the best at something unless that is indeed true. Maybe this is the scientist in me getting annoyed, but your README reads to me more marketing and less truth. Maybe verify your claims and benchmark every Scala/Scala.js serialization framework with something other than nanobenchmarks, or reduce the over the top muscle-flexing in your README.

Also something I find very suspicious – the design of boopickle very closely resembles Scala Pickling, yet there's no mention of it anywhere. All the way down to à la carte pickling. The resemblance is uncanny. Really odd to me that you'd take a bunch of inspiration seemingly from Pickling, not mention it anywhere, and claim superiority so flagrantly. Not a good way to play along nicely in open source.

**Comment by ochrons** [comment]
Well, the statement is true for picklers that are available for both Scala _and_ Scala.js. It is of course trivial to disapprove that statement by replacing "Boopickle" with the name of another library, that is available for both Scala and Scala.js, is faster than Boopickle and produces more efficient results. When Boopickle was created, there weren't that many pickling libraries available for Scala.js, which is also reflected in the benchmarks that I have tried to keep up to date as new libraries have arrived.

The reason why speed and efficiency are promoted so visibly is because on Scala.js, Boopickle is clearly fastest (especially in decoding, which is the important part, in some cases by order of magnitude) and produces most efficient encoding. The benchmarks represent "typical" workloads in a frontend application, since that's what Boopickle is intended for, not for server-to-server serialization or for storage (as clearly indicated in the documentation).

Besides the binary coding, Boopickle is based mostly on Prickle (as clearly attributed to in the very first paragraph, with a link to the original project), which in turn is based on scala-js-pickling, which in turn is inspired by, surprise surprise, Scala Pickling. I'm not too surprised to see heavy resemblance between all these libraries, although I never looked at Scala Pickling source at all.

In fact my benchmarks revealed some serious perf issues in Prickle, which were later fixed. They also inspired people to improve on existing pickling libraries by creating new ones, as they could see there was a lot of room for improvement. All in all, Boopickle and its performance suite have helped improve the quality of pickling libraries for Scala.js.

**Comment by Ichoran** [comment]
@ochrons - I thought you were claiming that Boopickle was both the fastest for Scala _and_ the fastest for Scala.js, not that out of libraries that support both Scala and Scala.js (explicitly), Boopickle is the fastest.  That at least should be clarified.

(Also, at some point you're probably going to run into the situation where library X runs on both, but Boopickle is faster than it in one and it is faster than Boopickle in the other, but I guess you can cross that bridge when you come to it.)

**Comment by ochrons** [comment]
The wording has been updated to better reflect the intention. In other news, BooPickle 1.2.2 is now faster than ever, performing even better than ScalaProtoBuffers for normal case class de/serialization ;)

**Comment by fommil** [comment]
@ochrons out of interest, why do you use pickling at all instead of fully compiletime approaches such as generic derivation via shapeless? The only runtime overhead is the object allocation and much of that can be optimised (from experience, I was marshalling terrabytes/second of JSON using this approach, which was on par with hand-rolled alternatives).

Related, I'm looking into making "semi auto" derivation easier to use and easier to code for if that's something you'd be interested in getting involved in. I'll be at Scala World. https://github.com/fommil/stalagmite/issues/38

**Comment by ochrons** [comment]
Boopickle is using "fully compiletime" pickler derivation via macros. I didn't go with shapeless because didn't want the additional dependency and back in the day shapeless was quite slow to compile :)

But definitely I'm interested in making the derivation easier and faster, as the current macro-code cannot handle all situations very well. Been waiting for scalameta to provide def-macros in addition to annotation-macros.

**Comment by fommil** [comment]
I've got the boilerplate for shapeless generics sorted. I think a macro to generate *that* is probably a good way to go, since shapeless handles a lot of the corner cases. That said, with semi-auto, the problem becomes a lot simpler to manage. https://github.com/fommil/dotfiles/tree/master/.emacs.d/snippets/scala-mode
