### ISSUE TITLE
Null on unpickling class hierarchy

### ISSUE THREAD

**Issue by cquiroz** [ochrons/boopickle#57]
This maybe a bug or just something to be documented. If I unpickle a class on a hierarchy using the parent class boopickle produces a null:

```scala
        sealed trait A
        case class B(v: Int) extends A

        val bytes = Pickle.intoBytes(B(1))
        println(Unpickle[B].fromBytes(bytes)) // This produces B(1)
        val bytes2 = Pickle.intoBytes(B(1))
        println(Unpickle[A].fromBytes(bytes2)) // This produces null
```

A workaround is to mark the pickled object with the root class

```scala
        val o: A = B(1)
        val bytes3 = Pickle.intoBytes(o)
        println(Unpickle[A].fromBytes(bytes3)) // This produces B(1)
```

**Comment by ochrons** [comment]
This is expected behaviour, as pickling a trait also encodes information about which implementation is being pickled, but if you just pickle an implementation, the unpickler cannot find this information.

Depending on the implementation, some JSON based picklers would exhibit similar behavior, if the implementation class type is missing from the JSON when you try to unpickle `A`.

The documentation sort of refers to this behaviour in https://github.com/ochrons/boopickle#complex-type-hierarchies but it's not exactly this use case. Improvement PRs to the documentation are most welcome :laughing:

**Comment by cquiroz** [comment]
It is strange for scala APIs to return null, would an exception be a better choice? I guess returning an `Either` would be another choice though it would complicate the API

**Comment by ochrons** [comment]
It depends on what it reads from the stream. There are special codes for values like `null`, so if that is read, then a `null` is returned. As the docs state, Boopickle is inherently unsafe because it does not store any meta information in the stream.
