### ISSUE TITLE
Support unpickling a Seq[ByteBuffer]

### ISSUE THREAD

**Issue by slandelle** [ochrons/boopickle#7]
Payloads might be transmitted over multiple paquets.

Currently, the only way is unpickle such payload is to copy into a global large ByteBuffer.
It could be possible to save this extra copy, and support unpickling a sequence of ByteBuffers. The only trick is you have still to use an intermediate ByeBuffer when a value is split over 2 consecutive ByteBuffers.

**Comment by ochrons** [comment]
This could be supported by building a `ByteString` like construct on top of the buffer sequence that would expose `ByteBuffer` interface. One issue is that on JS for example String decoding expects the buffer to have an underlying Typed Array, which is accessed directly.

**Comment by slandelle** [comment]
I don't think you need the whole ByteBuffer interface, probably just a subset. I guess you can afford copying the paquets into a single buffer on the JavaScript side. But it's a waste on the JVM one.

**Comment by slandelle** [comment]
Please let me know if I can help on the JVM side. I must say I'm not familiar with the Javascript one...

**Comment by ochrons** [comment]
If you want, this can be done outside the BooPickle implementation just by providing your own `ByteBuffer` implementation encapsulating the sequence. If you inspect the code, it uses only a few methods of `ByteBuffer` so it should be quite easy to implement. Of course special care has to be taken when crossing the buffer boundary, for example when reading a 4-byte integer split into two buffers.

Because these kinds of checks slow down performance quite a lot, I doubt it would be beneficial compared to just joining the buffers by simple copying in the first place.

**Comment by slandelle** [comment]
I guess you're right and such strategy could only make a difference on huge payload.
In my use case, I think I'll usually be under one MTU.

I'm closing the issue. I'll reopen if I do end up writing such a ByteBuffer and will contribute it then.

Thanks for your time.
